---

site_name: Implementaci贸n de Zentyal en AWS
docs_dir: '../../docs/es/'
site_dir: '../../generated/es/'

## https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/logo.svg                    # The logo is shared by all languages
  favicon: assets/images/favicon.ico              # The favicon is shared by all languages
  language: es                                    # The build's language
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - navigation.top

extra:             # Language Selection
  alternate:

    # Switch to Spanish
    - name: Spanish
      link: /es/
      lang: es

    # Switch to English
    - name: English
      link: /en/
      lang: en

plugins:
  - search:
      lang: es     # Set language for search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - Home: 'index.md'
  - AWS: 'aws-configuration.md'
  - Instalaci贸n: 'zentyal-installation.md'
  - Configuraci贸n: 'zentyal-configuration.md'
  - Certificados: 'zentyal-certificates.md'
  - Hardening: 'zentyal-hardening.md'
  - Backup: 'backup.md'
  - Monitorizaci贸n: 'monitoring.md'
  - Mantenimiento: 'maintenance.md'
  - Recovery: 'recovery.md'
  - Bug fixing: 'bug-fixing.md'
  - Sobre mi: 'about.md'

...
