---
#####
## Plantilla base
#####

site_author: Daniel Joven
site_name: Zentyal & AWS
site_url: https://zentyal.projects.djoven.es
docs_dir: 'docs'
site_dir: '/generated'

nav:
  - Home: 'index.md'
  - AWS: 'aws-configuration.md'
  - Instalación: 'zentyal-installation.md'
  - Configuración: 'zentyal-configuration.md'
  - Certificados: 'zentyal-certificates.md'
  - Hardening: 'zentyal-hardening.md'
  - Backup: 'backup.md'
  - Monitorización: 'monitoring.md'
  - Mantenimiento: 'maintenance.md'
  - Recovery: 'recovery.md'
  - Bug fixing: 'zentyal-bug-fixing.md'
  - Sobre mi: 'about.md'

## https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration

theme:
  name: material
  # custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  # logo: assets/images/logo.png                    # The logo is shared by all languages
  # favicon: assets/images/favicon.ico              # The favicon is shared by all languages
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      lang:
        - es
        - en
  - tags
  ## https://github.com/ultrabug/mkdocs-static-i18n
  - i18n:
      default_language: es
      docs_structure: suffix
      languages:
        es:
          name: Spanish
          build: true
        en:
          name: English
          build: true
      material_alternate: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

...
