---

## https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  language: es

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

site_name: Implementación de Zentyal
nav:
  - Home: 'index.md'
  - AWS: 'aws.md'
  - Instalación: 'zentyal-installation.md'
  - Configuración: 'zentyal-configuration.md'
  - Certificados: 'zentyal-certificates.md'
  - Securización: 'zentyal-hardening.md'
  - Monitorización: 'monitoring.md'
  - Mantenimiento: 'maintenance.md'
  - Sobre mi: 'about.md'

...
