---

INHERIT: ../mkdocs-common.yml

site_author: Daniel Joven
site_name: Implementaci贸n de Zentyal en AWS
site_url: https://zentyal.projects.djoven.es/en/
docs_dir: '../../docs/en'
site_dir: '../../generated/en'

theme:
  language: en                                    # The build's language

plugins:
  - search:
      lang: en     # Set language for search

nav:
  - Home: 'index.md'
  - AWS: 'aws-configuration.md'
  - Instalaci贸n: 'zentyal-installation.md'
  - Configuraci贸n: 'zentyal-configuration.md'
  - Certificados: 'zentyal-certificates.md'
  - Hardening: 'zentyal-hardening.md'
  - Backup: 'backup.md'
  - Monitorizaci贸n: 'monitoring.md'
  - Mantenimiento: 'maintenance.md'
  - Recovery: 'recovery.md'
  - Bug fixing: 'zentyal-bug-fixing.md'
  - Sobre mi: 'about.md'
...
